#!/usr/bin/env python

import warnings
warnings.filterwarnings('ignore')

import sys
import os.path
from pathlib import Path

import qiime2
from q2_types.per_sample_sequences import PairedEndFastqManifestPhred33V2
import qiime2.plugins.demux.actions as demux_actions


if len(sys.argv) != 3:
    print('USAGE: auto-qc fq-manifest output-dir')
    exit(0)

manifest_fp = Path(sys.argv[1])
output_dir = Path(sys.argv[2])

if not manifest_fp.exists():
    raise FileNotFoundError("Specified manifest file path does not exist: "
                            f"{manifest_fp}")

try:
    output_dir.mkdir()
except FileExistsError:
    raise FileExistsError(f"Specified output directory exists: {output_dir}\n"
                          "Won't overwrite.")

demux_art = qiime2.Artifact.import_data(
                type="SampleData[PairedEndSequencesWithQuality]",
                view=manifest_fp,
                view_type=PairedEndFastqManifestPhred33V2)

demux_art.save(output_dir / 'demux.qza')

demux_viz, = demux_actions.summarize(demux_art)

demux_viz.save(output_dir / 'demux.qzv')

print('\nSuccess!\n')

